### ISSUE TITLE
Model output inconsistent with other SAT solvers

### ISSUE THREAD

**Issue by wintered** [Udopia/candy-kingdom#45]
I find it puzzling that the candy model option seems to output partial models and not models.

```
cat formula.cnf         
p cnf 2 2  
2 1 0   
2 -1 0    
```

```
candy -model formula.cnf
... 
s SATISFIABLE
v 2 0
```

Other SAT solvers (e.g. minisat, glucose, cadical, abcd_sat)  would output a truth value for variable 1 in the don't care case which I would have expected from candy as well.

**Comment by Udopia** [comment]
Thank you for the hint, the issue was introduced by accident with the new object "CandyResult" which will serve more purposes in the futuer (among which is the handling of eliminated variables)
